#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "HVCompilerDefines.h"
#import "HVNSErrorHelper.h"
#import "HVSystemCapabilities.h"
#import "HVCrashDoctor.h"
#import "HVNSDictionaryHelper.h"
#import "HVCrashReportFilterAlert.h"
#import "HVCrashReportFilterAppleFmt.h"
#import "HVCrashReportFilterBasic.h"
#import "HVCrashReportFilterDoctor.h"
#import "HVCrashReportFilterJSON.h"
#import "HVCrashReportFilterSets.h"
#import "HVCrashReportFilterStringify.h"
#import "HVCString.h"
#import "HVVarArgs.h"
#import "HVCrashInstallation+Private.h"
#import "HVCrashInstallation.h"
#import "HVCrashInstallationStandard.h"
#import "HVCrash+Private.h"
#import "HVCrashAppMemory+Private.h"
#import "HVCrashCachedData.h"
#import "HVCrashConfiguration+Private.h"
#import "HVCrashReportC.h"
#import "HVCrashReportFixer.h"
#import "HVCrashReportStoreC+Private.h"
#import "HVCrashReportVersion.h"
#import "HVCrash.h"
#import "HVCrashAppMemory.h"
#import "HVCrashAppMemoryTracker.h"
#import "HVCrashAppStateTracker.h"
#import "HVCrashAppTransitionState.h"
#import "HVCrashC.h"
#import "HVCrashCConfiguration.h"
#import "HVCrashConfiguration.h"
#import "HVCrashError.h"
#import "HVCrashMonitorType.h"
#import "HVCrashReport.h"
#import "HVCrashReportFields.h"
#import "HVCrashReportFilter.h"
#import "HVCrashReportStore.h"
#import "HVCrashReportStoreC.h"
#import "HVCrashReportWriter.h"
#import "HVCrashMonitorContextHelper.h"
#import "HVCrashMonitor_AppState.h"
#import "HVCrashMonitor_CPPException.h"
#import "HVCrashMonitor_Deadlock.h"
#import "HVCrashMonitor_MachException.h"
#import "HVCrashMonitor_Memory.h"
#import "HVCrashMonitor_NSException.h"
#import "HVCrashMonitor_Signal.h"
#import "HVCrashMonitor_System.h"
#import "HVCrashMonitor_User.h"
#import "HVCrashMonitor_Zombie.h"
#import "HVObjCApple.h"
#import "HVCPU.h"
#import "HVCPU_Apple.h"
#import "HVCrashMonitor.h"
#import "HVCrashMonitorContext.h"
#import "HVCrashMonitorFlag.h"
#import "HVCrashMonitorHelper.h"
#import "HVCxaThrowSwapper.h"
#import "HVDate.h"
#import "HVDebug.h"
#import "HVDynamicLinker.h"
#import "HVFileUtils.h"
#import "HVID.h"
#import "HVJSONCodec.h"
#import "HVJSONCodecObjC.h"
#import "HVLogger.h"
#import "HVMach-O.h"
#import "HVMach.h"
#import "HVMachineContext.h"
#import "HVMachineContext_Apple.h"
#import "HVMemory.h"
#import "HVObjC.h"
#import "HVPlatformSpecificDefines.h"
#import "HVSignalInfo.h"
#import "HVStackCursor.h"
#import "HVStackCursor_Backtrace.h"
#import "HVStackCursor_MachineContext.h"
#import "HVStackCursor_SelfThread.h"
#import "HVString.h"
#import "HVSymbolicator.h"
#import "HVSysCtl.h"
#import "HVThread.h"

FOUNDATION_EXPORT double HVCrashGuardVersionNumber;
FOUNDATION_EXPORT const unsigned char HVCrashGuardVersionString[];

